// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: events.proto

package pb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type UserCreated struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,json=iD,proto3" json:"ID,omitempty"`
	Version              int32    `protobuf:"varint,2,opt,name=Version,json=version,proto3" json:"Version,omitempty"`
	At                   int64    `protobuf:"varint,3,opt,name=At,json=at,proto3" json:"At,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=Name,json=name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCreated) Reset()         { *m = UserCreated{} }
func (m *UserCreated) String() string { return proto.CompactTextString(m) }
func (*UserCreated) ProtoMessage()    {}
func (*UserCreated) Descriptor() ([]byte, []int) {
	return fileDescriptor_events_917244aaeec0da62, []int{0}
}
func (m *UserCreated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCreated.Unmarshal(m, b)
}
func (m *UserCreated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCreated.Marshal(b, m, deterministic)
}
func (dst *UserCreated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCreated.Merge(dst, src)
}
func (m *UserCreated) XXX_Size() int {
	return xxx_messageInfo_UserCreated.Size(m)
}
func (m *UserCreated) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCreated.DiscardUnknown(m)
}

var xxx_messageInfo_UserCreated proto.InternalMessageInfo

func (m *UserCreated) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *UserCreated) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *UserCreated) GetAt() int64 {
	if m != nil {
		return m.At
	}
	return 0
}

func (m *UserCreated) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Payload struct {
	Type                 int32        `protobuf:"varint,1,opt,name=Type,json=type,proto3" json:"Type,omitempty"`
	T1                   *UserCreated `protobuf:"bytes,2,opt,name=T1,json=t1" json:"T1,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_events_917244aaeec0da62, []int{1}
}
func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (dst *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(dst, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Payload) GetT1() *UserCreated {
	if m != nil {
		return m.T1
	}
	return nil
}

func init() {
	proto.RegisterType((*UserCreated)(nil), "pb.UserCreated")
	proto.RegisterType((*Payload)(nil), "pb.Payload")
}

func init() { proto.RegisterFile("events.proto", fileDescriptor_events_917244aaeec0da62) }

var fileDescriptor_events_917244aaeec0da62 = []byte{
	// 178 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8e, 0x31, 0xab, 0x83, 0x30,
	0x14, 0x85, 0x49, 0x8c, 0x4f, 0xde, 0xb5, 0xb4, 0x90, 0x29, 0x5b, 0xc5, 0xc9, 0x49, 0xb0, 0xdd,
	0x0b, 0xa5, 0x2e, 0x5d, 0x4a, 0x09, 0xb6, 0x4b, 0xa7, 0x88, 0x77, 0x10, 0xaa, 0x09, 0xf1, 0x22,
	0xf8, 0xef, 0x8b, 0xe9, 0xd2, 0xf1, 0x70, 0xce, 0xf9, 0xf8, 0x60, 0x83, 0x33, 0x8e, 0x34, 0x95,
	0xce, 0x5b, 0xb2, 0x92, 0xbb, 0x36, 0x7f, 0x41, 0xfa, 0x98, 0xd0, 0x5f, 0x3c, 0x1a, 0xc2, 0x4e,
	0x6e, 0x81, 0x5f, 0x6b, 0xc5, 0x32, 0x56, 0xfc, 0x6b, 0xde, 0xd7, 0x52, 0x41, 0xf2, 0x44, 0x3f,
	0xf5, 0x76, 0x54, 0x3c, 0x63, 0x45, 0xac, 0x93, 0xf9, 0x1b, 0xd7, 0xe5, 0x99, 0x54, 0x94, 0xb1,
	0x22, 0xd2, 0xdc, 0x90, 0x94, 0x20, 0x6e, 0x66, 0x40, 0x25, 0xc2, 0x57, 0x8c, 0x66, 0xc0, 0xfc,
	0x04, 0xc9, 0xdd, 0x2c, 0x6f, 0x6b, 0xba, 0xb5, 0x6e, 0x16, 0x87, 0x01, 0x1d, 0x6b, 0x41, 0x8b,
	0x43, 0xb9, 0x07, 0xde, 0x54, 0x81, 0x9b, 0x1e, 0x76, 0xa5, 0x6b, 0xcb, 0x1f, 0x13, 0xcd, 0xa9,
	0x6a, 0xff, 0x82, 0xe7, 0xf1, 0x13, 0x00, 0x00, 0xff, 0xff, 0x3c, 0xb0, 0xb5, 0x60, 0xb7, 0x00,
	0x00, 0x00,
}
