// Code generated by snapsource. DO NOT EDIT.
// source: commands.proto

package pb


// AggregateID implements the snapsource.Command interface for CreateUser
func (c *CreateUser) AggregateID() string {
	return c.ID
}


// AggregateID implements the snapsource.Command interface for UpdateEmail
func (c *UpdateEmail) AggregateID() string {
	return c.ID
}

