// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: commands.proto

package pb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type CreateUser struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,json=iD,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=Name,json=name,proto3" json:"Name,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=Email,json=email,proto3" json:"Email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUser) Reset()         { *m = CreateUser{} }
func (m *CreateUser) String() string { return proto.CompactTextString(m) }
func (*CreateUser) ProtoMessage()    {}
func (*CreateUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_commands_6127f72953c4dc1d, []int{0}
}
func (m *CreateUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUser.Unmarshal(m, b)
}
func (m *CreateUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUser.Marshal(b, m, deterministic)
}
func (dst *CreateUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUser.Merge(dst, src)
}
func (m *CreateUser) XXX_Size() int {
	return xxx_messageInfo_CreateUser.Size(m)
}
func (m *CreateUser) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUser.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUser proto.InternalMessageInfo

func (m *CreateUser) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *CreateUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type UpdateEmail struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,json=iD,proto3" json:"ID,omitempty"`
	NewEmail             string   `protobuf:"bytes,2,opt,name=NewEmail,json=newEmail,proto3" json:"NewEmail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateEmail) Reset()         { *m = UpdateEmail{} }
func (m *UpdateEmail) String() string { return proto.CompactTextString(m) }
func (*UpdateEmail) ProtoMessage()    {}
func (*UpdateEmail) Descriptor() ([]byte, []int) {
	return fileDescriptor_commands_6127f72953c4dc1d, []int{1}
}
func (m *UpdateEmail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateEmail.Unmarshal(m, b)
}
func (m *UpdateEmail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateEmail.Marshal(b, m, deterministic)
}
func (dst *UpdateEmail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateEmail.Merge(dst, src)
}
func (m *UpdateEmail) XXX_Size() int {
	return xxx_messageInfo_UpdateEmail.Size(m)
}
func (m *UpdateEmail) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateEmail.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateEmail proto.InternalMessageInfo

func (m *UpdateEmail) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *UpdateEmail) GetNewEmail() string {
	if m != nil {
		return m.NewEmail
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateUser)(nil), "pb.CreateUser")
	proto.RegisterType((*UpdateEmail)(nil), "pb.UpdateEmail")
}

func init() { proto.RegisterFile("commands.proto", fileDescriptor_commands_6127f72953c4dc1d) }

var fileDescriptor_commands_6127f72953c4dc1d = []byte{
	// 142 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xce, 0xcf, 0xcd,
	0x4d, 0xcc, 0x4b, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x72,
	0xe3, 0xe2, 0x72, 0x2e, 0x4a, 0x4d, 0x2c, 0x49, 0x0d, 0x2d, 0x4e, 0x2d, 0x12, 0xe2, 0xe3, 0x62,
	0xf2, 0x74, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0xca, 0x74, 0x11, 0x12, 0xe2, 0x62,
	0xf1, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x01, 0x8b, 0xb0, 0xe4, 0x25, 0xe6, 0xa6, 0x0a, 0x89, 0x70,
	0xb1, 0xba, 0xe6, 0x26, 0x66, 0xe6, 0x48, 0xb0, 0x82, 0x05, 0x59, 0x53, 0x41, 0x1c, 0x25, 0x4b,
	0x2e, 0xee, 0xd0, 0x82, 0x94, 0xc4, 0x92, 0x54, 0xb0, 0x1c, 0x86, 0x41, 0x52, 0x5c, 0x1c, 0x7e,
	0xa9, 0xe5, 0x10, 0x7d, 0x4c, 0x60, 0x51, 0x8e, 0x3c, 0x28, 0x3f, 0x89, 0x0d, 0xec, 0x1a, 0x63,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x78, 0x43, 0xce, 0xce, 0x9f, 0x00, 0x00, 0x00,
}
